### ISSUE TITLE
Arbitrary limit to single-digit version parts

### ISSUE THREAD

**Issue by daren-thomas** [lord-executor/Toggl2Vertec#1]
See:

https://github.com/lord-executor/Toggl2Vertec/blob/6e0e46c6f2d7eaed40fd73295e750d2c3b0ba58b/scripts/release.ps1#L29

Using this script to create releases will be interesting when, say, the revision number goes to double-digits...

**Comment by elca-lan** [comment]
😜😘

**Comment by lord-executor** [comment]
Now this has a _proper_ regex which should solve the issue
```
$manifest.url = $manifest.url -replace "/v\d+\.\d+\.\d+/","/$gitTag/"
```
